project:
  type: website
  output-dir: docs

website:
  title: "Jaeim Paik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Viz
        menu:
         - text: Olympics 2026
           href: data_viz/Tidy Analysis.qmd
         - text: Ecotourism
           href: data_viz/Tidy Analysis 2.qmd

format:
  html:
    theme:
      - cosmo
      - litera
    css: styles.css
    toc: true
    page-layout: full
