---
title: "About Me"
---

## Education

POMONA COLLEGE Claremont, CA:
Bachelor of Arts, Cognitive Science & Data Science

UNITED WORLD COLLEGE OF SOUTHEAST ASIA (UWCSEA) - EAST CAMPUS Singapore, Singapore:
IBDP Diploma

## Work experiences

**HUMAN CENTERED DESIGN (HCD) Claremont, CA**

Teaching Assistant 2025 - Present
● Supported student learning and growth through in-class constructive critiques, office hours, and written feedback on three ~6-week projects, tailoring guidance to individual student needs; Coordinated logistics for a 20-person
course, collaborating closely with faculty and co-TAs on curriculum, timelines, and rubrics

**ASSOCIATED STUDENTS OF POMONA COLLEGE (ASPC) Claremont, CA**
ASPC Director of Community Partnerships 2025 - 2026
● Coordinated between Pomona College & City of Claremont to recruit and support 12+ civic engagement interns;
led collaborations between City Hall and 5C classes to increase student interaction w/ Claremont community

**PIONEER RESEARCH PROGRAM South Korea**
Student Research Facilitator 2025 - Present
● Facilitated online research seminars for 100+ high school students, fostering inclusive discussion and critical
thinking; Mentored students on research methods, data interpretation, and clear communication of insights
ADDITIONAL LEADERSHIP EXPERIENCE

**POMONA COLLEGE SUSTAINABILITY DEPARTMENT Claremont, CA**
Ecorep, social media manager & bulletin writer 2025 - Present
● Served as a peer educator directing students to Sustainability Department resources and encouraging discourse
around sustainable practices; Co-executed 5 on-campus events (30-40+ attendees each) with other 5C clubs

**INTERNATIONAL STUDENT MENTORSHIP PROGRAM (ISMP) Claremont, CA**
Student Mentor 2025 - Present
● Provided weekly, personalized academic, social, and emotional support to first-year international students,
connecting them with campus resources; Organized cultural events for 40+ participants, building community

**ASIAN AMERICAN MENTORSHIP PROGRAM (AAMP) Claremont, CA**
Student Mentor 2025 - Present
● Co-mentored 9 first-year students through biweekly check-ins, offering individualized guidance and
encouragement to support their transition to college; Planned bonding and off-campus events, including a 50+
attendee snack event, to foster peer connection and belonging